name: Latest Medium blog post workflow
on:
  schedule:
    # Berjalan setiap hari pada tengah malam
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM-POST"
          feed_list: "https://medium.com/feed/@kemaltf_"
          max_post_count: 5
          commit_message: "Update Medium blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}